databases:
  - name: postgres
    ipAllowList: []
    databaseName: tweetarapi
    user: tweetarapi

services:
  - type: web
    name: tweetarapi
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false